# Generated by Django 3.0.8 on 2020-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auther',
            field=models.CharField(default='ssu', max_length=100),
        ),
    ]
